org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=false

# Platform
minecraft_version=26.1.2
neoforge_version=26.1.2.95
moddevgradle_version=2.0.144
cloth_config_version=26.1.154

# Mod properties
mod_id=greatchasms
mod_version=1.0.0
maven_group=com.zachary
archives_base_name=greatchasms
